name: Frp Client
version: 1.0.1
slug: frp_client
description: Fast reverse proxy client for Home Assistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: default
ports:
  80/tcp: 80
  443/tcp: 443
options:
  server_addr: frps.example.com
  server_port: 7000
  token: ""
  tunnels: []
schema:
  server_addr: str
  server_port: int
  token: str
  tunnels:
    - name: str
      type: str
      local_ip: str
      local_port: int
      remote_port: int
